######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 18 11:49:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
