######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 18 11:06:48 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
