######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 16:28:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h jfq.h
SOURCES += adder.cpp main.cpp
