#if !defined(AFX_MCD_H__537D4CD3_4A23_4D2F_A46D_79CDA8C52107__INCLUDED_)
#define AFX_MCD_H__537D4CD3_4A23_4D2F_A46D_79CDA8C52107__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMcd wrapper class

class CMcd : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMcd)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd8b46f41, 0xf4ac, 0x4799, { 0xb5, 0x9d, 0x7b, 0x5b, 0xf6, 0x50, 0x36, 0xf4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetDirection();
	void SetDirection(BOOL);

// Operations
public:
	void SetNumbers(long x, long y);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MCD_H__537D4CD3_4A23_4D2F_A46D_79CDA8C52107__INCLUDED_)
