######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 14:57:28 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mytime.h
SOURCES += main.cpp mytime.cpp
