######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 10:01:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += adder.cpp
