######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 18 16:35:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qqlogin.cpp
