######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 09:19:00 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += changevalue.cpp
