######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 18 15:13:57 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += parentwin.cpp
