######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 17:00:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += qq.h qqlogin.h
SOURCES += main.cpp qqlogin.cpp
