######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 18 14:31:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += closelab.cpp
