######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 11:05:01 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h
SOURCES += adder.cpp main.cpp
